clear;
echo "RPiToolbox - installing git and node";
sudo apt install git;
curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -;
sudo apt-get install -y nodejs;
echo "RPiToolbox - cloning spatial edge server";
git clone https://github.com/ptcrealitylab/vuforia-spatial-edge-server.git;
cd vuforia-spatial-edge-server;
npm install;
npm audit fix;
echo "RPiToolbox - initializing core addon";
git submodule update --init --recursive;
cd addons/vuforia-spatial-core-addon;
npm install;
cd ..;
echo "RPiToolbox - installing basic interfaces";
git clone https://github.com/ptcrealitylab/vuforia-spatial-basic-interfaces-addon.git;
cd vuforia-spatial-basic-interfaces-addon;
npm install;
cd ../..;
npm install;
npm audit fix;